### ISSUE TITLE
Cucumber - chef setup hang(different from the before mentioned)

### ISSUE THREAD

**Issue by metalsok** [Atalanta/cucumber-chef#129]
Hello again , had the same "hang problem" again when the gem happens and at the moment when nokogiri gem is installed. Specifically it asks for libxml. So i solved it by editing the bootstrap file by installing before the nokogiri installation this libxml.
So now i am on another issue with is described bellow.
Thank you for installing Chef!
- export PATH=/opt/chef/embedded/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
- PATH=/opt/chef/embedded/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
- tee /tmp/chef-solo/Gemfile
- cat
  source 'https://rubygems.org'
  gem 'chef', '10.24.0'
  gem 'berkshelf'
  gem 'moneta', '< 0.7.0'
- tee /tmp/chef-solo/Berksfile
- cat
  site :opscode
  cookbook 'chef-server'
- gem install bundler --no-ri --no-rdoc
  Fetching: bundler-1.3.5.gem (100%)
  Successfully installed bundler-1.3.5
  1 gem installed
- bundle install --standalone --path vendor/bundle --binstubs
  Fetching gem metadata from https://rubygems.org/........
  Fetching gem metadata from https://rubygems.org/..
  Resolving dependencies...
  Installing i18n (0.6.4) 
  Installing multi_json (1.7.7) 
  Installing activesupport (3.2.14) 
  Installing addressable (2.3.5) 
  Installing builder (3.2.2) 
  Installing gyoku (1.0.0) 
  Installing nokogiri (1.5.10) 
  Installing akami (1.2.0) 
  Installing buff-ruby_engine (0.1.0) 
  Installing buff-shell_out (0.1.0) 
  Installing timers (1.1.0) 
  Installing celluloid (0.14.1) 
  Installing hashie (2.0.5) 
  Installing chozo (0.6.1) 
  Installing multipart-post (1.2.0) 
  Installing faraday (0.8.7) 
  Installing minitar (0.5.4) 
  Installing rbzip2 (0.2.0) 
  Installing retryable (1.3.3) 
  Installing buff-extensions (0.5.0) 
  Installing nio4r (0.4.6) 
  Installing celluloid-io (0.14.1) 
  Installing erubis (2.7.0) 
  Installing json (1.7.7) 
  Installing mixlib-log (1.6.0) 
  Installing mixlib-authentication (1.3.0) 
  Installing net-http-persistent (2.9) 
  Installing net-ssh (2.6.8) 
  Installing solve (0.6.1) 
  Installing varia_model (0.1.1) 
  Installing ffi (1.9.0) 
  Installing gssapi (1.0.3) 
  Installing httpclient (2.2.0.2) 
  Installing little-plugger (1.1.3) 
  Installing logging (1.6.2) 
  Installing rubyntlm (0.1.1) 
  Installing rack (1.5.2) 
  Installing httpi (0.9.7) 
  Installing nori (1.1.5) 
  Installing wasabi (1.0.0) 
  Installing savon (0.9.5) 
  Installing uuidtools (2.1.4) 
  Installing winrm (1.1.2) 
  Installing ridley (1.2.4) 
  Installing thor (0.18.1) 
  Installing berkshelf (2.0.7) 
  Installing bunny (0.7.9) 
  Installing highline (1.6.19) 
  Installing mixlib-cli (1.3.0) 
  Installing mixlib-config (1.1.2) 
  Installing mixlib-shellout (1.2.0) 
  Installing moneta (0.6.0) 
  Installing net-ssh-gateway (1.2.0) 
  Installing net-ssh-multi (1.1) 
  Installing ipaddress (0.8.0) 
  Installing systemu (2.5.2) 
  Installing yajl-ruby (1.1.0) 
  Installing ohai (6.18.0) 
  Installing mime-types (1.23) 
  Installing rest-client (1.6.7) 
  Installing polyglot (0.3.3) 
  Installing treetop (1.4.14) 
  Installing chef (10.24.0) 
  Using bundler (1.3.5) 
  Your bundle is complete!
  It was installed into ./vendor/bundle
  Post-install message from bunny:
  [Version 0.7.8] test suite cleanup (eliminated some race conditions related to queue.message_count)
- mv -v /tmp/chef-solo/cookbooks /tmp/chef-solo/site-cookbooks
  `/tmp/chef-solo/cookbooks' ->`/tmp/chef-solo/site-cookbooks'
- bin/berks install --path /tmp/chef-solo/cookbooks/
  Installing chef-server (2.0.0) from site: 'http://cookbooks.opscode.com/api/v1/cookbooks'
- chef-solo --config /etc/chef/solo.rb --json-attributes /tmp/chef-solo/attributes.json --logfile /var/log/chef/chef-solo.log --log_level debug
  [2013-07-25T11:30:02+00:00] INFO: **\* Chef 10.24.0 ***
  [2013-07-25T11:30:05+00:00] DEBUG: Building node object for cucumber-chef.test-lab
  [2013-07-25T11:30:05+00:00] DEBUG: Extracting run list from JSON attributes provided on command line
  [2013-07-25T11:30:05+00:00] INFO: Setting the run_list to ["recipe[chef-server::rubygems-install]", "recipe[chef-server::apache-proxy]", "role[test_lab]"] from JSON
  [2013-07-25T11:30:05+00:00] DEBUG: Applying attributes from json file
  [2013-07-25T11:30:05+00:00] DEBUG: Platform is ubuntu version 12.04
  [2013-07-25T11:30:05+00:00] INFO: Run List is [recipe[chef-server::rubygems-install], recipe[chef-server::apache-proxy], role[test_lab]]
  [2013-07-25T11:30:05+00:00] INFO: Run List expands to [chef-server::rubygems-install, chef-server::apache-proxy, cucumber-chef]
  [2013-07-25T11:30:05+00:00] INFO: Starting Chef Run for cucumber-chef.test-lab
  [2013-07-25T11:30:05+00:00] INFO: Running start handlers
  [2013-07-25T11:30:05+00:00] INFO: Start handlers complete.
  [2013-07-25T11:30:05+00:00] DEBUG: No chefignore file found at /tmp/chef-solo/cookbooks/chefignore no files will be ignored
  [2013-07-25T11:30:05+00:00] DEBUG: No chefignore file found at /tmp/chef-solo/site-cookbooks/chefignore no files will be ignored
  [2013-07-25T11:30:05+00:00] DEBUG: Loading cookbook chef-server's library file: /tmp/chef-solo/cookbooks/chef-server/libraries/omnitruck_client.rb
  [2013-07-25T11:30:05+00:00] DEBUG: Loading cookbook chef-server's library file: /tmp/chef-solo/cookbooks/chef-server/libraries/dev_helper.rb
  [2013-07-25T11:30:05+00:00] DEBUG: Node cucumber-chef.test-lab loading cookbook chef-server's attribute file /tmp/chef-solo/cookbooks/chef-server/attributes/default.rb
  [2013-07-25T11:30:05+00:00] DEBUG: Node cucumber-chef.test-lab loading cookbook cucumber-chef's attribute file /tmp/chef-solo/site-cookbooks/cucumber-chef/attributes/default.rb
  [2013-07-25T11:30:05+00:00] DEBUG: Loading Recipe chef-server::rubygems-install via include_recipe
# 
# Recipe Compile Error
## Chef::Exceptions::RecipeNotFound

could not find recipe rubygems-install for cookbook chef-server

[2013-07-25T11:30:05+00:00] DEBUG: Re-raising exception: Chef::Exceptions::RecipeNotFound - could not find recipe rubygems-install for cookbook chef-server
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.24.0/lib/chef/cookbook_version.rb:547:in `load_recipe'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.24.0/lib/chef/mixin/language_include_recipe.rb:46:in`load_recipe'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.24.0/lib/chef/mixin/language_include_recipe.rb:33:in `block in include_recipe'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.24.0/lib/chef/mixin/language_include_recipe.rb:27:in`each'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.24.0/lib/chef/mixin/language_include_recipe.rb:27:in `include_recipe'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.24.0/lib/chef/run_context.rb:79:in`block in load'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.24.0/lib/chef/run_context.rb:75:in `each'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.24.0/lib/chef/run_context.rb:75:in`load'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.24.0/lib/chef/client.rb:198:in `setup_run_context'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.24.0/lib/chef/client.rb:418:in`do_run'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.24.0/lib/chef/client.rb:176:in `run'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.24.0/lib/chef/application.rb:140:in`run_chef_client'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.24.0/lib/chef/application/solo.rb:224:in `block in run_application'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.24.0/lib/chef/application/solo.rb:216:in`loop'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.24.0/lib/chef/application/solo.rb:216:in `run_application'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.24.0/lib/chef/application.rb:72:in`run'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.24.0/bin/chef-solo:25:in `<top (required)>'
  /usr/bin/chef-solo:23:in`load'
  /usr/bin/chef-solo:23:in `<main>'
[2013-07-25T11:30:05+00:00] ERROR: Running exception handlers
[2013-07-25T11:30:05+00:00] ERROR: Exception handlers complete
[2013-07-25T11:30:05+00:00] FATAL: Stacktrace dumped to /tmp/chef-solo/chef-stacktrace.out

My question is. Am i on the right track of trying to make this thing work by editing the bootstrap file? any suggestions regarding the problem above? as i understand some recipes from the chef-server cookbook are required(according to the .json ) and to be exact chef-server::rubygems-install ,  but they do not exist.

Thank you in advance!

**Comment by zpatten** [comment]
Sorry for the late reply, it might be around two weeks before I can really look into this; I am moving this weekend and both the rest of this week and next week are pretty shot for me to do anything other than my "day job" if you will.  That being said I might be able to do some recon into this if the time comes up.  Just wanted to let you know I haven't forgotten about ya.
