### ISSUE TITLE
cucumber-nagios is not installed on Test Lab

### ISSUE THREAD

**Issue by arp** [Atalanta/cucumber-chef#35]
That's what I get:

```
$ cucumber-chef test base
Cucumber-chef project: base sucessfully uploaded to the test lab.
no such file to load -- cucumber/nagios/steps (LoadError)
/usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
/home/ubuntu/base/features/support/env.rb:6
/usr/lib/ruby/gems/1.8/gems/cucumber-1.0.2/bin/../lib/cucumber/rb_support/rb_language.rb:143:in `load'
/usr/lib/ruby/gems/1.8/gems/cucumber-1.0.2/bin/../lib/cucumber/rb_support/rb_language.rb:143:in `load_code_file'
/usr/lib/ruby/gems/1.8/gems/cucumber-1.0.2/bin/../lib/cucumber/runtime/support_code.rb:176:in `load_file'
/usr/lib/ruby/gems/1.8/gems/cucumber-1.0.2/bin/../lib/cucumber/runtime/support_code.rb:78:in `load_files!'
/usr/lib/ruby/gems/1.8/gems/cucumber-1.0.2/bin/../lib/cucumber/runtime/support_code.rb:77:in `each'
/usr/lib/ruby/gems/1.8/gems/cucumber-1.0.2/bin/../lib/cucumber/runtime/support_code.rb:77:in `load_files!'
/usr/lib/ruby/gems/1.8/gems/cucumber-1.0.2/bin/../lib/cucumber/runtime.rb:137:in `load_step_definitions'
/usr/lib/ruby/gems/1.8/gems/cucumber-1.0.2/bin/../lib/cucumber/runtime.rb:39:in `run!'
/usr/lib/ruby/gems/1.8/gems/cucumber-1.0.2/bin/../lib/cucumber/cli/main.rb:43:in `execute!'
/usr/lib/ruby/gems/1.8/gems/cucumber-1.0.2/bin/../lib/cucumber/cli/main.rb:20:in `execute'
/usr/lib/ruby/gems/1.8/gems/cucumber-1.0.2/bin/cucumber:14
/usr/bin/cucumber:19:in `load'
/usr/bin/cucumber:19
```

The problem goes away after ssh'ing to Test Lab and running

```
gem install cucumber-nagios
```

**Comment by arp** [comment]
I believe the intent is that cucumber-chef should require cucumber-nagios as a dependency. At least, that's what I see in cucumber-chef.gemspec.

But that doesn't seem to work:

```
$ git clone https://github.com/Atalanta/cucumber-chef
$ cd cucumber-chef/
$ gem build cucumber-chef.gemspec
  Successfully built RubyGem
  Name: cucumber-chef
  Version: 1.0.3
  File: cucumber-chef-1.0.3.gem
$ gem install cucumber-chef-1.0.3.gem
Successfully installed cucumber-chef-1.0.3
1 gem installed
Building YARD (yri) index for cucumber-chef-1.0.3...
[warn]: Could not find extra file: LICENSE.txt
$ gem list cucumber-nagios                                                                                                             

*** LOCAL GEMS ***


$ gem list cucumber-chef

*** LOCAL GEMS ***

cucumber-chef (1.0.3)
```

**Comment by arp** [comment]
BTW, ubuntu_ami is also not installed automatically as a dependency. Needed to install that one manually.

**Comment by Atalanta** [comment]
This is no longer a dependency - in the RC release we have pulled in the step definitions from cucumber-nagios into this tool.
