### ISSUE TITLE
NameError in displayconfig when trying to determine ami automatically

### ISSUE THREAD

**Issue by yoniLavi** [Atalanta/cucumber-chef#54]
Version: cucumber-chef-1.0.4
## Steps to reproduce
1. Configure knife.rb without aws_image_id (but with ubuntu_release, aws_instance_arch and aws_instance_type)
2. Run cucumber-chef displayconfig
## Expected

ubuntu-ami library should be used to determine the ami automatically (issue #20)
## Actual

```
/var/lib/gems/1.9.1/gems/cucumber-chef-1.0.4/lib/cucumber/chef/config.rb:87:in `aws_image_id': uninitialized constant UbuntuAmi (NameError)
    from /var/lib/gems/1.9.1/gems/cucumber-chef-1.0.4/lib/cucumber/chef/config.rb:66:in `list'
    from /var/lib/gems/1.9.1/gems/cucumber-chef-1.0.4/bin/cucumber-chef:77:in `displayconfig'
    from /var/lib/gems/1.9.1/gems/thor-0.15.2/lib/thor/task.rb:27:in `run'
    from /var/lib/gems/1.9.1/gems/thor-0.15.2/lib/thor/invocation.rb:120:in `invoke_task'
    from /var/lib/gems/1.9.1/gems/thor-0.15.2/lib/thor.rb:275:in `dispatch'
    from /var/lib/gems/1.9.1/gems/thor-0.15.2/lib/thor/base.rb:408:in `start'
    from /var/lib/gems/1.9.1/gems/cucumber-chef-1.0.4/bin/cucumber-chef:123:in `<top (required)>'
    from /usr/local/bin/cucumber-chef:19:in `load'
    from /usr/local/bin/cucumber-chef:19:in `<main>'
```
## Possible explanation

The class used for the query object(config.rb:87) seems to be wrong. Maybe it needs to use Ec2AmisUbuntu?

**Comment by Atalanta** [comment]
This should be fixed in RC,
