### ISSUE TITLE
2.0.0.rc1 - logger silently fails if it can't find a .chef directory

### ISSUE THREAD

**Issue by Atalanta** [Atalanta/cucumber-chef#58]
sns@tdi:~$ cucumber-chef displayconfig
/home/sns/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/cucumber-chef-2.0.0.rc1/bin/cucumber-chef:335:in `rescue in displayconfig': undefined method`fatal' for nil:NilClass (NoMethodError)
    from /home/sns/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/cucumber-chef-2.0.0.rc1/bin/cucumber-chef:328:in `displayconfig'
    from /home/sns/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thor-0.15.2/lib/thor/task.rb:27:in`run'
    from /home/sns/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thor-0.15.2/lib/thor/invocation.rb:120:in `invoke_task'
    from /home/sns/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thor-0.15.2/lib/thor.rb:275:in`dispatch'
    from /home/sns/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thor-0.15.2/lib/thor/base.rb:408:in `start'
    from /home/sns/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/cucumber-chef-2.0.0.rc1/bin/cucumber-chef:407:in`<top (required)>'
    from /home/sns/.rbenv/versions/1.9.3-p194/bin/cucumber-chef:23:in `load'
    from /home/sns/.rbenv/versions/1.9.3-p194/bin/cucumber-chef:23:in`<main>'
sns@tdi:~$ vi /home/sns/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/cucumber-chef-2.0.0.rc1/bin/cucumber-chef
sns@tdi:~$ vi /home/sns/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/cucumber-chef-2.0.0.rc1/bin/cucumber-chef

Digging deeper, this seems to fail because of the logger constructor failing to find a parent of .chef.

**Comment by Atalanta** [comment]
Workaround - ensure there's a .chef directory in cwd...

**Comment by Atalanta** [comment]
Fixed.
