### ISSUE TITLE
Tags do not combine correctly

### ISSUE THREAD

**Issue by pikesley** [Atalanta/cucumber-chef#70]
I have this at the top of my feature:

```
@score @directories
```

If I run this

```
cucumber-chef test --tags @directories,@score
```

then it works, but it's ORing them together, so it runs all of my features tagged with '@score', which is not what I want. As far as I understand cucumber, running this

```
cucumber-chef test --tags @directories --tags @score
```

should AND those tags together and run the subset I want, but it actually craps out with

```
Using features directory: /Users/sam/amee-chef/features
Cucumber-Chef Test Runner Initalized!
Cleaning up any previous test runs...done.
Uploading files required for this test run...done.
Executing Cucumber-Chef Test Runner
Using the default profile...
No such file or directory - @score (Errno::ENOENT)
/usr/lib/ruby/gems/1.8/gems/cucumber-1.2.1/bin/../lib/cucumber/feature_file.rb:55:in `initialize'
/usr/lib/ruby/gems/1.8/gems/cucumber-1.2.1/bin/../lib/cucumber/feature_file.rb:55:in `open'
/usr/lib/ruby/gems/1.8/gems/cucumber-1.2.1/bin/../lib/cucumber/feature_file.rb:55:in `source'
/usr/lib/ruby/gems/1.8/gems/cucumber-1.2.1/bin/../lib/cucumber/feature_file.rb:37:in `parse'
/usr/lib/ruby/gems/1.8/gems/cucumber-1.2.1/bin/../lib/cucumber/runtime/features_loader.rb:28:in `load'
/usr/lib/ruby/gems/1.8/gems/cucumber-1.2.1/bin/../lib/cucumber/runtime/features_loader.rb:26:in `each'
/usr/lib/ruby/gems/1.8/gems/cucumber-1.2.1/bin/../lib/cucumber/runtime/features_loader.rb:26:in `load'
/usr/lib/ruby/gems/1.8/gems/cucumber-1.2.1/bin/../lib/cucumber/runtime/features_loader.rb:14:in `features'
/usr/lib/ruby/gems/1.8/gems/cucumber-1.2.1/bin/../lib/cucumber/runtime.rb:170:in `features'
/usr/lib/ruby/gems/1.8/gems/cucumber-1.2.1/bin/../lib/cucumber/runtime.rb:46:in `run!'
/usr/lib/ruby/gems/1.8/gems/cucumber-1.2.1/bin/../lib/cucumber/cli/main.rb:43:in `execute!'
/usr/lib/ruby/gems/1.8/gems/cucumber-1.2.1/bin/../lib/cucumber/cli/main.rb:20:in `execute'
/usr/lib/ruby/gems/1.8/gems/cucumber-1.2.1/bin/cucumber:14
/usr/bin/cucumber:19:in `load'
/usr/bin/cucumber:19
```

It would be really nice if this worked :/

**Comment by zpatten** [comment]
Ya looks like cucumber is actually what's blowing up there; I'll try to reproduce.

**Comment by zpatten** [comment]
I've done a new release; this should now be fixed if you can please test.

**Comment by pikesley** [comment]
Oh yeah, that worked! Thanks, this is a massive help :)

**Comment by zpatten** [comment]
Awesome; good to hear!
