### ISSUE TITLE
cucumber-chef setup errors

### ISSUE THREAD

**Issue by sameersegal** [Atalanta/cucumber-chef#84]
Hi, I am getting the following error on 'cucumber-chef setup'. I tried searching for a solution on the internet but couldn't make much sense of what I read.

```
Provisioning cucumber-chef test lab platform.
Waiting for instance...done.
Waiting for 20 seconds...done.
Waiting for SSHD...done.
Bootstrapping AWS EC2 instance...done.
Waiting for Chef-Server...done.
Waiting for Chef-WebUI...done.
Downloading chef-server credentials...done.
Building 'cc-knife' configuration...done.
Uploading cucumber-chef cookbooks...//Users/Sameer/.rvm/gems/ruby-1.9.3-p194/gems/cucumber-chef-2.0.4/lib/cucumber/chef/provisioner.rb:175:in `block (2 levels) in upload_cookbook': undefined method `upload_cookbooks' for #<Chef::CookbookUploader:0x007fa9d1e60b18> (NoMethodError)
    from /Users/Sameer/.rvm/gems/ruby-1.9.3-p194/gems/chef-0.10.10/lib/chef/cookbook_loader.rb:107:in `block in each'
    from /Users/Sameer/.rvm/gems/ruby-1.9.3-p194/gems/chef-0.10.10/lib/chef/cookbook_loader.rb:106:in `each'
    from /Users/Sameer/.rvm/gems/ruby-1.9.3-p194/gems/chef-0.10.10/lib/chef/cookbook_loader.rb:106:in `each'
    from /Users/Sameer/.rvm/gems/ruby-1.9.3-p194/gems/cucumber-chef-2.0.4/lib/cucumber/chef/provisioner.rb:173:in `block in upload_cookbook'
    from /Users/Sameer/.rvm/gems/ruby-1.9.3-p194/gems/cucumber-chef-2.0.4/lib/cucumber/chef/utility.rb:109:in `spinner'
    from /Users/Sameer/.rvm/gems/ruby-1.9.3-p194/gems/cucumber-chef-2.0.4/lib/cucumber/chef/provisioner.rb:170:in `upload_cookbook'
    from /Users/Sameer/.rvm/gems/ruby-1.9.3-p194/gems/cucumber-chef-2.0.4/lib/cucumber/chef/provisioner.rb:62:in `build'
    from /Users/Sameer/.rvm/gems/ruby-1.9.3-p194/gems/cucumber-chef-2.0.4/bin/cucumber-chef:149:in `setup'
    from /Users/Sameer/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.16.0/lib/thor/task.rb:27:in `run'
    from /Users/Sameer/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.16.0/lib/thor/invocation.rb:120:in `invoke_task'
    from /Users/Sameer/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.16.0/lib/thor.rb:275:in `dispatch'
    from /Users/Sameer/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.16.0/lib/thor/base.rb:425:in `start'
    from /Users/Sameer/.rvm/gems/ruby-1.9.3-p194/gems/cucumber-chef-2.0.4/bin/cucumber-chef:453:in `<top (required)>'
    from /Users/Sameer/.rvm/gems/ruby-1.9.3-p194/bin/cucumber-chef:19:in `load'
    from /Users/Sameer/.rvm/gems/ruby-1.9.3-p194/bin/cucumber-chef:19:in `<main>'
```

The .cucumber-chef/cucumber-chef.log shows:

```
cat <<EOF > /etc/chef/first-boot.json
{"run_list":"role[test_lab]","cucumber_chef":{"version":"2.0.4","prerelease":false}}
EOF

touch ${CUCUMBER_CHEF_BOOTSTRAP_DONE}
')
2012-09-18 01:36:41.934480 | 12672 |  INFO | ssh.rb:124:download | parameters(/home/ubuntu/.chef/Sameer.pem,/Users/Sameer/Documents/Code/Chef/Deployment/Test/chef-repo/.cucumber-chef/Sameer.pem)
2012-09-18 01:36:41.934725 | 12672 |  INFO | ssh.rb:128:block in download | download(/home/ubuntu/.chef/Sameer.pem -> /Users/Sameer/Documents/Code/Chef/Deployment/Test/chef-repo/.cucumber-chef/Sameer.pem)
2012-09-18 01:36:43.515802 | 12672 |  INFO | ssh.rb:136:block in download | finish
2012-09-18 01:36:43.515953 | 12672 |  INFO | ssh.rb:124:download | parameters(/home/ubuntu/.chef/validation.pem,/Users/Sameer/Documents/Code/Chef/Deployment/Test/chef-repo/.cucumber-chef/validation.pem)
2012-09-18 01:36:43.516089 | 12672 |  INFO | ssh.rb:128:block in download | download(/home/ubuntu/.chef/validation.pem -> /Users/Sameer/Documents/Code/Chef/Deployment/Test/chef-repo/.cucumber-chef/validation.pem)
2012-09-18 01:36:44.904527 | 12672 |  INFO | ssh.rb:136:block in download | finish
```

I unable to ssh with cucumber-chef ssh and get Could not locate file '.cucumber-chef/id_rsa-ubuntu'.

Let me know if you need server side log. Thank you for the help in advance.
- Sameer

**Comment by zpatten** [comment]
In a recent release of Chef, the method call was changed from `upload_cookbook` to `upload_cookbooks`.  Looks like your running on an older version of Chef; bundle update your Chef gem and the problem should go away.  Latest Chef is `0.10.14`, seems your on `0.10.10`.

**Comment by sameersegal** [comment]
Thanks - did a `gem update chef` solved the issue

**Comment by zpatten** [comment]
No problem; glad to help!
