### ISSUE TITLE
cucumber-chef setup fails

### ISSUE THREAD

**Issue by athiele** [Atalanta/cucumber-chef#89]
Hi,

I am trying to get cucumber-chef working, so I followed the instructions on the wiki page. After configuring, cucumber-chef setup shows the following error.

```
$ cucumber-chef setup

Provisioning cucumber-chef test lab platform.
Waiting for instance...done.
Waiting for 20 seconds...done.
Waiting for SSHD...done.
Bootstrapping AWS EC2 instance...done.
Waiting for Chef-Server...done.
Waiting for Chef-WebUI...done.
Downloading chef-server credentials...done.
Building 'cc-knife' configuration...done.
Uploading cucumber-chef cookbooks...|/usr/local/rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/net/http.rb:762:in `initialize': Error connecting to http://46.51.157.37:4000/sandboxes - Connection timed out - connect(2) (Errno::ETIMEDOUT)
        from /usr/local/rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/net/http.rb:762:in `open'
        from /usr/local/rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/net/http.rb:762:in `block in connect'
        from /usr/local/rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/timeout.rb:54:in `timeout'
        from /usr/local/rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/timeout.rb:99:in `timeout'
        from /usr/local/rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/net/http.rb:762:in `connect'
        from /usr/local/rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/net/http.rb:755:in `do_start'
        from /usr/local/rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/net/http.rb:744:in `start'
        from /usr/local/rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/net/http.rb:1284:in `request'
        from /usr/local/rvm/gems/ruby-1.9.3-p362/gems/rest-client-1.6.7/lib/restclient/net_http_ext.rb:51:in `request'
        from /usr/local/rvm/gems/ruby-1.9.3-p362/gems/chef-10.16.4/lib/chef/rest/rest_request.rb:99:in `block in call'
        from /usr/local/rvm/gems/ruby-1.9.3-p362/gems/chef-10.16.4/lib/chef/rest/rest_request.rb:114:in `hide_net_http_bug'
        from /usr/local/rvm/gems/ruby-1.9.3-p362/gems/chef-10.16.4/lib/chef/rest/rest_request.rb:98:in `call'
        from /usr/local/rvm/gems/ruby-1.9.3-p362/gems/chef-10.16.4/lib/chef/rest.rb:251:in `block in raw_http_request'
        from /usr/local/rvm/gems/ruby-1.9.3-p362/gems/chef-10.16.4/lib/chef/rest.rb:363:in `retriable_rest_request'
        from /usr/local/rvm/gems/ruby-1.9.3-p362/gems/chef-10.16.4/lib/chef/rest.rb:249:in `raw_http_request'
        from /usr/local/rvm/gems/ruby-1.9.3-p362/gems/chef-10.16.4/lib/chef/rest.rb:243:in `api_request'
        from /usr/local/rvm/gems/ruby-1.9.3-p362/gems/chef-10.16.4/lib/chef/rest.rb:144:in `post_rest'
        from /usr/local/rvm/gems/ruby-1.9.3-p362/gems/chef-10.16.4/lib/chef/cookbook_uploader.rb:71:in `upload_cookbooks'
        from /usr/local/rvm/gems/ruby-1.9.3-p362/gems/cucumber-chef-2.0.7/lib/cucumber/chef/provisioner.rb:175:in `block (2 levels) in upload_cookbook'
        from /usr/local/rvm/gems/ruby-1.9.3-p362/gems/chef-10.16.4/lib/chef/cookbook_loader.rb:107:in `block in each'
        from /usr/local/rvm/gems/ruby-1.9.3-p362/gems/chef-10.16.4/lib/chef/cookbook_loader.rb:106:in `each'
        from /usr/local/rvm/gems/ruby-1.9.3-p362/gems/chef-10.16.4/lib/chef/cookbook_loader.rb:106:in `each'
        from /usr/local/rvm/gems/ruby-1.9.3-p362/gems/cucumber-chef-2.0.7/lib/cucumber/chef/provisioner.rb:173:in `block in upload_cookbook'
        from /usr/local/rvm/gems/ruby-1.9.3-p362/gems/cucumber-chef-2.0.7/lib/cucumber/chef/utility.rb:109:in `spinner'
        from /usr/local/rvm/gems/ruby-1.9.3-p362/gems/cucumber-chef-2.0.7/lib/cucumber/chef/provisioner.rb:170:in `upload_cookbook'
        from /usr/local/rvm/gems/ruby-1.9.3-p362/gems/cucumber-chef-2.0.7/lib/cucumber/chef/provisioner.rb:62:in `build'
        from /usr/local/rvm/gems/ruby-1.9.3-p362/gems/cucumber-chef-2.0.7/bin/cucumber-chef:149:in `setup'
        from /usr/local/rvm/gems/ruby-1.9.3-p362/gems/thor-0.16.0/lib/thor/task.rb:27:in `run'
        from /usr/local/rvm/gems/ruby-1.9.3-p362/gems/thor-0.16.0/lib/thor/invocation.rb:120:in `invoke_task'
        from /usr/local/rvm/gems/ruby-1.9.3-p362/gems/thor-0.16.0/lib/thor.rb:275:in `dispatch'
        from /usr/local/rvm/gems/ruby-1.9.3-p362/gems/thor-0.16.0/lib/thor/base.rb:425:in `start'
        from /usr/local/rvm/gems/ruby-1.9.3-p362/gems/cucumber-chef-2.0.7/bin/cucumber-chef:462:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-1.9.3-p362/bin/cucumber-chef:19:in `load'
        from /usr/local/rvm/gems/ruby-1.9.3-p362/bin/cucumber-chef:19:in `<main>'
        from /usr/local/rvm/gems/ruby-1.9.3-p362/bin/ruby_noexec_wrapper:14:in `eval'
        from /usr/local/rvm/gems/ruby-1.9.3-p362/bin/ruby_noexec_wrapper:14:in `<main>'

```

Has anyone an idea what is going wrong here? Google does not return any usable results for that error message.

Thanks in advance,
Aimo

**Comment by athiele** [comment]
Hi again,

I found out that my firewall was blocking Port 4000 - Problem solved,

Best regards,
Aimo
